### ISSUE TITLE
Unable to build on Mac OS Sierra with XCode 8.3.2

### ISSUE THREAD

**Issue by kahneraja** [SwiftGit2/SwiftGit2#92]
When i `git clone this repo` and `carthage update` i get the following error.

```
...
org.carthage.CarthageKit/DerivedData/Nimble/v5.1.1/Build/Intermediates/Nimble.build/Release-appletvsimulator/Nimble-tvOS.build/Objects-normal/x86_64/Functional.o -o /Users/kahneraja/Library/Caches/org.carthage.CarthageKit/DerivedData/Nimble/v5.1.1/Build/Intermediates/Nimble.build/Release-appletvsimulator/Nimble-tvOS.build/Objects-normal/x86_64/Match.o
/Users/kahneraja/Workspace/SwiftGit2/Carthage/Checkouts/Nimble/Sources/Nimble/Utils/Errors.swift:15:30: warning: conditional cast from 'T' to 'CustomDebugStringConvertible' always succeeds
        if let error = error as? CustomDebugStringConvertible {
                             ^
/Users/kahneraja/Workspace/SwiftGit2/Carthage/Checkouts/Nimble/Sources/Lib/CwlPreconditionTesting/CwlPreconditionTesting/CwlCatchBadInstructionPOSIX.swift:89:5: error: 'setjmp' is unavailable: Functions that may return more than one time (annotated with the 'returns_twice' attribute) are unavailable in Swift
        if setjmp(&env.0) != 0 {
           ^~~~~~
Darwin.setjmp:2:13: note: 'setjmp' has been explicitly marked unavailable here
public func setjmp(_: UnsafeMutablePointer<Int32>!) -> Int32
            ^

** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

any points or advice around these errors?

**Comment by kahneraja** [comment]
My goal is to build a git client application rather than work on porting libgit2 to swift.

**Comment by mdiep** [comment]
What platform are you building for?

> When i `git clone this repo` and `carthage update` i get the following error.

If you're cloning this repo and building it there, you shouldn't run `carthage update`. SwiftGit2 builds its dependencies itself through Xcode.

**Comment by kahneraja** [comment]
I'm working on a new ios app aiming for 10.3.

When carthage fails in this way I am then able to open the solution in xcode ane build.

When i build i get an assortment of openssl and ssh build errors related to permissions etc...

I guess what I'm trying to figure out right now is...

For an app that is aiming to only git clone and git push without branching, history, or resolving merge conflicts... what is the simplest way to build a light way swift 3 git client app?

Is there a lightweight git over http approach you might recommend?

**Comment by kahneraja** [comment]
Are. It looks like #84 address my problem.

Will try `brew install cmake libssh2` and see if that helps.

**Comment by kahneraja** [comment]
And thank you @mdiep. I didnt realise...

> SwiftGit2 builds its dependencies itself through Xcode.

**Comment by kahneraja** [comment]
hmmm. interesting. i still get the following set of issues:
```
Building libssh2 for iphonesimulator10.2 x86_64
Please stand by...
/Users/pivotal/workspace/gitmarkdown/SwiftGit2/External/libssh2-ios/bin/iphonesimulator10.2-x86_64.sdk/build-libssh2.log
Command /bin/sh failed with exit code 1
...
Building fat binary...
cp: /tmp/openssl-i386/include/openssl: No such file or directory
fatal error: lipo: can't open input file: /tmp/openssl-x86_64/lib/libcrypto.a (No such file or directory)
fatal error: lipo: can't open input file: /tmp/openssl-x86_64/lib/libssl.a (No such file or directory)
Building done.
Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure
```
![image](https://cloud.githubusercontent.com/assets/5403386/25528765/515e4f5e-2bed-11e7-8534-7b53a971863c.png)

**Comment by mdiep** [comment]
Closed because of the comment here: https://github.com/SwiftGit2/SwiftGit2/issues/84#issuecomment-298168691
